import { describe, expect, it } from 'vitest';
import { analyze, type SignalLabel } from '../src/core/signal';
import type { Interval } from '../src/core/types';
import { parseBinanceKlines, parseBinanceSymbols, parseBinanceTicker } from '../src/data/binance';
import { aggregateCandles, parseCoinbaseCandles, parseCoinbaseProducts, parseCoinbaseStats } from '../src/data/coinbase';

/**
 * The e2e suite replays e2e/fixtures/api/ (generated by e2e/fixtures/make-fixtures.mjs). This
 * pins down which signal each payload produces, so the e2e expectations have a known source.
 */
const FILES = import.meta.glob<string>('../e2e/fixtures/api/**/*.json', { query: '?raw', import: 'default', eager: true });
/** Just after the fixtures were "recorded": every candle has closed. */
const RECORDED_NOW = Date.UTC(2026, 8, 20, 21);

const json = (path: string): unknown => {
  const text = FILES[`../e2e/fixtures/api/${path}`];
  if (text === undefined) throw new Error(`missing fixture ${path}`);
  return JSON.parse(text);
};

describe('e2e fixture payloads', () => {
  it.each<[string, Interval, SignalLabel]>([
    ['BTC', '4h', 'STRONG_BULLISH'],
    ['BTC', '1h', 'BULLISH'],
    ['BTC', '1d', 'NEUTRAL'],
    ['ETH', '4h', 'BEARISH'],
    ['SOL', '4h', 'NEUTRAL'],
    ['XRP', '4h', 'NEUTRAL'],
    ['DOGE', '4h', 'STRONG_BEARISH'],
    ['BNB', '4h', 'STRONG_BULLISH'],
    ['ADA', '4h', 'BEARISH'],
    ['AVAX', '4h', 'BULLISH'],
    ['LINK', '4h', 'STRONG_BULLISH'],
  ])('Binance %s %s → %s', (symbol, interval, expected) => {
    const candles = parseBinanceKlines(json(`binance/klines-${symbol}USDT-${interval}.json`), interval);
    expect(candles).toHaveLength(200);
    const outcome = analyze(candles, { now: RECORDED_NOW });
    expect(outcome.ok && outcome.analysis.signal).toBe(expected);
    const ticker = parseBinanceTicker(json(`binance/ticker-${symbol}USDT.json`));
    expect(ticker.lastPrice).toBe(candles.at(-1)!.close);
  });

  it('FRESH has too little history for an analysis', () => {
    const candles = parseBinanceKlines(json('binance/klines-FRESHUSDT-4h.json'), '4h');
    expect(analyze(candles, { now: RECORDED_NOW })).toMatchObject({ ok: false, reason: 'insufficient-data', got: 40 });
  });

  it('the Binance price list offers the fixture symbols for search', () => {
    const bases = parseBinanceSymbols(json('binance/ticker-price.json'), 'USDT');
    expect(bases).toEqual(expect.arrayContaining(['BTC', 'LINK', 'LTC', 'LDO', 'PEPE', 'FRESH']));
    expect(bases).not.toContain('LUNC');
  });

  it.each<[string, Interval, number, SignalLabel]>([
    ['BTC', '1h', 3600, 'BULLISH'],
    ['BTC', '4h', 3600, 'BULLISH'],
    ['BTC', '1d', 86400, 'NEUTRAL'],
    ['ETH', '4h', 3600, 'BEARISH'],
  ])('Coinbase %s %s → %s', (symbol, interval, granularity, expected) => {
    const hourly = parseCoinbaseCandles(json(`coinbase/candles-${symbol}-USD-${granularity}.json`), granularity);
    const candles = interval === '4h' ? aggregateCandles(hourly, 4 * 3_600_000) : hourly;
    const outcome = analyze(candles.slice(-200), { now: RECORDED_NOW });
    expect(outcome.ok && outcome.analysis.signal).toBe(expected);
    const stats = parseCoinbaseStats(json(`coinbase/stats-${symbol}-USD.json`));
    expect(stats.lastPrice).toBeGreaterThan(0);
    expect(stats.changePct24h).not.toBeNull();
  });

  it('Coinbase products list USD markets, without BNB', () => {
    const bases = parseCoinbaseProducts(json('coinbase/products.json'), 'USD');
    expect(bases).toContain('LINK');
    expect(bases).not.toContain('BNB');
    expect(bases).not.toContain('OLD');
  });
});
