/**
 * Builds CSS selectors for the element the user picked. Prefers what survives redesigns and
 * re-renders (ids, test ids, schema.org props, meaningful class names) over position, and
 * skips generated names (CSS-in-JS hashes, framework ids). Every candidate is verified to
 * match exactly the picked element before it's offered.
 */

/** Attributes developers keep stable on purpose, best first. */
export const STABLE_ATTRIBUTES = [
  'data-testid',
  'data-test-id',
  'data-test',
  'data-qa',
  'data-cy',
  'data-automation-id',
  'itemprop',
  'name',
] as const;

const GENERATED_PREFIX = /^(?:css|jsx|sc|svelte|astro|emotion|styled)-/i;
const GENERATED_INFIX = /(?:^|[-_])sc-|__sc-/;
const GENERATED_ID =
  /^(?:ember\d|ext-gen|gwt-uid|yui_|react-select-\d|headlessui-|radix-|mui-\d|rc_select|__bvid__|ui-id-\d|mat-[\w-]*\d|cdk-[\w-]*\d|j_id|ctl\d|:|«)/i;
const STATE_CLASS =
  /^(?:is-|has-)|^(?:active|current|selected|open|opened|closed|show|shown|hide|hidden|visible|hover|hovered|focus|focused|disabled|expanded|collapsed|loading|loaded|in|fade|animated|sticky|clearfix)$/i;
const SIMPLE_IDENT = /^-?[A-Za-z_][A-Za-z0-9_-]*$/;

/** A segment that looks like a hash: "1x2y3z", "Xy1Z2", "bdVaJa", "x1n2onr6". */
function isRandomSegment(segment: string): boolean {
  if (segment.length < 5) return false;
  const digits = (segment.match(/\d/g) ?? []).length;
  const letters = (segment.match(/[A-Za-z]/g) ?? []).length;
  if (digits > 0 && letters > 0) return true;
  if (segment.length <= 8 && digits === 0) {
    const upper = (segment.match(/[A-Z]/g) ?? []).length;
    const lower = letters - upper;
    // Irregular casing like "bdVaJa" or "AxjAm" (not "productTitle" or "Header").
    if (upper >= 2 && lower >= 2 && !/^[A-Z][a-z]+[A-Z][a-z]+$/.test(segment)) return true;
  }
  return false;
}

/** Class names and ids generated by build tools (CSS modules, CSS-in-JS, atomic CSS). */
export function isHashedToken(token: string): boolean {
  if (!token || token.length > 48) return true;
  if (GENERATED_PREFIX.test(token) || GENERATED_INFIX.test(token)) return true;
  return token.split(/[-_]+/).some(isRandomSegment);
}

export function isStableClass(name: string): boolean {
  return SIMPLE_IDENT.test(name) && !STATE_CLASS.test(name) && !isHashedToken(name);
}

export function isStableId(id: string): boolean {
  if (!id || id.length > 64 || /\s/.test(id)) return false;
  if (/^\d/.test(id) || GENERATED_ID.test(id) || /[:«»]/.test(id)) return false;
  return !isHashedToken(id);
}

export function isStableAttributeValue(value: string): boolean {
  return value.length > 0 && value.length <= 80 && !/[\n\r]/.test(value) && !isHashedToken(value.replace(/\s+/g, '-'));
}

/** CSS.escape (https://drafts.csswg.org/cssom/#serialize-an-identifier), usable outside browsers. */
export function cssEscape(value: string): string {
  let result = '';
  const first = value.charCodeAt(0);
  for (let i = 0; i < value.length; i++) {
    const code = value.charCodeAt(i);
    if (code === 0) {
      result += '\uFFFD';
    } else if (
      (code >= 0x1 && code <= 0x1f) ||
      code === 0x7f ||
      (i === 0 && code >= 0x30 && code <= 0x39) ||
      (i === 1 && code >= 0x30 && code <= 0x39 && first === 0x2d)
    ) {
      result += `\\${code.toString(16)} `;
    } else if (i === 0 && value.length === 1 && code === 0x2d) {
      result += `\\${value[i]}`;
    } else if (
      code >= 0x80 ||
      code === 0x2d ||
      code === 0x5f ||
      (code >= 0x30 && code <= 0x39) ||
      (code >= 0x41 && code <= 0x5a) ||
      (code >= 0x61 && code <= 0x7a)
    ) {
      result += value[i];
    } else {
      result += `\\${value[i]}`;
    }
  }
  return result;
}

/** A double-quoted CSS string for attribute selectors. */
export function cssString(value: string): string {
  return `"${value.replace(/["\\]/g, '\\$&').replace(/\n/g, '\\a ')}"`;
}

export function isUniqueMatch(root: ParentNode, selector: string, element: Element): boolean {
  try {
    const found = root.querySelectorAll(selector);
    return found.length === 1 && found[0] === element;
  } catch {
    return false;
  }
}

function tagOf(element: Element): string {
  return cssEscape(element.localName);
}

function stableClasses(element: Element, max = 2): string[] {
  const classes: string[] = [];
  for (const name of Array.from(element.classList)) {
    if (isStableClass(name) && !classes.includes(name)) classes.push(name);
    if (classes.length >= max) break;
  }
  return classes;
}

/** "#price" or "[data-testid=\"price\"]" when the element carries a stable, unique handle. */
function anchorFor(element: Element, root: ParentNode): string | null {
  if (element.id && isStableId(element.id)) {
    const selector = `#${cssEscape(element.id)}`;
    if (isUniqueMatch(root, selector, element)) return selector;
  }
  for (const attribute of STABLE_ATTRIBUTES) {
    const value = element.getAttribute(attribute);
    if (value === null || !isStableAttributeValue(value)) continue;
    const bare = `[${attribute}=${cssString(value)}]`;
    if (isUniqueMatch(root, bare, element)) return bare;
    const tagged = `${tagOf(element)}${bare}`;
    if (isUniqueMatch(root, tagged, element)) return tagged;
  }
  return null;
}

function sameTagIndex(element: Element): { index: number; count: number } {
  let index = 0;
  let count = 0;
  const parent = element.parentElement;
  if (!parent) return { index: 1, count: 1 };
  for (let sibling = parent.firstElementChild; sibling; sibling = sibling.nextElementSibling) {
    if (sibling.localName !== element.localName) continue;
    count++;
    if (sibling === element) index = count;
  }
  return { index, count };
}

/** One step of a path: tag, up to two stable classes, and a position only when siblings are alike. */
function segmentFor(element: Element, useClasses: boolean): string {
  const classes = useClasses ? stableClasses(element) : [];
  const base = `${tagOf(element)}${classes.map((name) => `.${cssEscape(name)}`).join('')}`;
  const parent = element.parentElement;
  if (!parent) return base;
  let alike = 0;
  for (let sibling = parent.firstElementChild; sibling; sibling = sibling.nextElementSibling) {
    if (sibling.localName === element.localName && classes.every((name) => sibling.classList.contains(name))) alike++;
  }
  if (alike <= 1) return base;
  return `${base}:nth-of-type(${sameTagIndex(element).index})`;
}

/**
 * Shortest unique path, starting at the nearest ancestor with a stable handle. A path without
 * a handle is only accepted once it names a class: "p:nth-of-type(2)" may be unique today by
 * coincidence, but it breaks as soon as another paragraph pair appears anywhere.
 */
function anchoredPath(element: Element, root: ParentNode): string | null {
  const parts: string[] = [];
  let named = false;
  for (let node: Element | null = element; node && node.localName !== 'html'; node = node.parentElement) {
    const anchor = anchorFor(node, root);
    if (anchor) {
      parts.unshift(anchor);
      return parts.join(' > ');
    }
    const segment = segmentFor(node, true);
    named ||= segment.includes('.');
    parts.unshift(segment);
    const selector = parts.join(' > ');
    if ((named || node.localName === 'body') && isUniqueMatch(root, selector, element)) return selector;
  }
  return null;
}

/** Last resort: position-only path from <body>. Always unique, but breaks when the layout moves. */
function structuralPath(element: Element): string {
  const parts: string[] = [];
  for (let node: Element | null = element; node && node.localName !== 'html'; node = node.parentElement) {
    if (node.localName === 'body') {
      parts.unshift('body');
      break;
    }
    parts.unshift(segmentFor(node, false));
  }
  return parts.join(' > ');
}

/**
 * Up to `max` selectors for the element, most robust first, each verified to match only
 * that element in `root` (its document by default).
 */
export function selectorCandidates(element: Element, max = 4, root: ParentNode = element.ownerDocument): string[] {
  const candidates: string[] = [];
  const add = (selector: string | null) => {
    if (selector && !candidates.includes(selector) && isUniqueMatch(root, selector, element)) candidates.push(selector);
  };
  add(anchorFor(element, root));
  add(anchoredPath(element, root));
  const own = segmentFor(element, true);
  const parent = element.parentElement;
  if (parent && parent.localName !== 'html') {
    const parentAnchor = anchorFor(parent, root);
    if (parentAnchor) add(`${parentAnchor} ${own.replace(/:nth-of-type\(\d+\)$/, '')}`);
  }
  add(structuralPath(element));
  return candidates.slice(0, max);
}

/** Short label for the picker: "span#price.amount". */
export function describeElement(element: Element): string {
  let label = element.localName;
  if (element.id && element.id.length <= 32) label += `#${element.id}`;
  const classes = Array.from(element.classList)
    .filter((name) => !isHashedToken(name))
    .slice(0, 2);
  if (classes.length) label += `.${classes.join('.')}`;
  return label;
}
